# Generated by Django 5.2.14 on 2026-05-20 12:53

import django.db.models.deletion
import feedback.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('sent_to_provider', 'Sent to provider')], default='new', max_length=30)),
                ('kind', models.CharField(default='comment', max_length=40)),
                ('message', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True, max_length=1200)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_name', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('screenshot_path', models.CharField(blank=True, max_length=800)),
                ('screenshot_hash', models.CharField(blank=True, max_length=96)),
                ('screenshot_bytes', models.PositiveIntegerField(default=0)),
                ('screenshot_mime', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('external_id', models.CharField(max_length=240)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=320)),
                ('web_url', models.URLField(blank=True, max_length=1200)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_issue', to='feedback.feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('sent_to_provider', 'Sent to provider')], max_length=30)),
                ('actor', models.CharField(default='system', max_length=80)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('namespace', models.CharField(blank=True, max_length=240)),
                ('project_name', models.CharField(blank=True, max_length=240)),
                ('external_project_id', models.CharField(blank=True, max_length=240)),
                ('web_url', models.URLField(blank=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('create_mode', models.CharField(default='manual', max_length=20)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_targets', to='integrations.providerintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='issue_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.issuetarget'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('public_key', models.CharField(default=feedback.models.generate_public_key, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('widget_settings', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.organization')),
            ],
        ),
        migrations.AddField(
            model_name='issuetarget',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_target', to='feedback.project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.project'),
        ),
        migrations.CreateModel(
            name='ProjectPublicKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(default=feedback.models.generate_public_key, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='feedback.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderIssueAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('status', models.CharField(choices=[('due', 'Due'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='due', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_attempts', to='feedback.feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='feedback_pr_organiz_8647df_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['public_key'], name='feedback_pr_public__9b7bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['project', 'status', '-created_at'], name='feedback_fe_project_91343a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', '-created_at'], name='feedback_fe_status_212662_idx'),
        ),
    ]
