# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="screenshot_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="provider_attachment_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="provider_attachment_path",
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name="feedback",
            name="provider_attachment_provider",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="feedback",
            name="provider_attachment_raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="feedback",
            name="provider_attachment_url",
            field=models.URLField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name="externalissue",
            name="provider_attachment_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="externalissue",
            name="provider_attachment_url",
            field=models.URLField(blank=True, max_length=1200),
        ),
    ]
