# Generated by Django 5.2.14 on 2026-05-20 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reconnect', 'Needs reconnect'), ('disabled', 'Disabled')], default='connected', max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('external_account_id', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_integrations', to='workspaces.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(blank=True)),
                ('token_hint', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='integrations.providerintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='providerintegration',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_provider_integration_name'),
        ),
    ]
